name: Build and Export Serverino Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker build
    - name: Build Docker image
      run: |
        echo "FROM alpine:latest
        RUN apk add vim gcc musl-dev ldc dub llvm-libunwind-static openssl-libs-static gzip upx cmake make
        WORKDIR /app
        COPY . .
        CMD [\"dub\", \"--build=release-nobounds\"]" > Dockerfile
        docker build -t serverino-image .

    # Run the Docker container to build the project
    - name: Run Docker container and build project
      run: |
        docker run --name serverino-container serverino-image || true

    # Copy compiled file from Docker container to host
    - name: Copy compiled binary
      run: |
        docker cp serverino-container:/app/serverino-test .
        docker rm serverino-container

    # Upload the binary as an artifact
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: serverino-test
        path: serverino-test
